surname = input('Geef de achternaam: ')
first_name = input('Geef de voornaam: ')
street = input('Geef de straatnaam: ')
number = input('Geef de huisnummer: ')
zip_code = input('Geef de postcode: ')
city = input('Geef de stad: ')
print(first_name, surname)
print(street, number)
print(zip_code, city)